### ISSUE TITLE
Documentation links are out of date

### ISSUE THREAD

**Issue by ebkalderon** [dremon/ipp.rs#5]
While using this crate, I ran into an issue where the actual API deviated from the documentation in several ways, namely:

* `IppAttributeList` not implementing `Debug`.
* `IppClient::send()` requiring a `&mut T: IppOperation` instead of simply a `T: IppOperation`.

After checking Docs.rs, I noticed that the official documentation linked in the `README.md` and in the `Cargo.toml` is out of date. It would be nice if these links could be updated to point to Docs.rs instead to avoid future confusion.

**EDIT:** Additionally, the usage example shown in the `README.md` is also inaccurate and out of date.

**Comment by dremon** [comment]
Thanks for the report, I'll try to update all of the mentioned in the coming days.

**Comment by dremon** [comment]
I've made a new release 0.2.1 with updated documentation.
