### ISSUE TITLE
Is printing from a buffer feasible?

### ISSUE THREAD

**Issue by eutampieri** [dremon/ipp.rs#6]
Can I `ipp::operation::PrintJob::new(buffer, &"pettorine", None);`, with buffer being a `Vec<u8>`?

Thanks in advance

**Comment by dremon** [comment]
You can perhaps use Cursor for that, although the current implementation takes ownership of the reader.

```rust
PrintJob::new(Box::new(io::Cursor::new(buffer)), ...)
```

**Comment by eutampieri** [comment]
Yes, that's totally fine! It works, Thanks!
